Ф-4 Верстка хедера
car-parking-tracking/Parking.client pull request #13
Opened 2023-07-28 10:39 UTC by mrHoft

1. Task: Верстка хедера
2. Screenshot:
![image](https://github.com/car-parking-tracking/Parking.client/assets/51874769/d8688d87-6592-4071-ad1c-4712f50c36fa)

3. Was done:
    - [x] Header
    - [x] Header positioning
    - [ ] Inner elements. Currently using templates.

Наследовался от ветки с картой чтоб вёрстка сошлась. Не тяните так долго со слияниями пожалуйста.
close #12

2023-07-28 10:54 UTC, shinonhorror requested changes

2023-07-28 10:54 UTC, shinonhorror commented on src/components/elements/header/header.tsx
> +`
Стили должны быть вынесены в отдельный файл

2023-07-28 10:54 UTC, shinonhorror commented on src/components/elements/header/header.tsx
> +        <p className="small">© Parkonaft 2023</p>
По архитектуре - используем атомы (атом descriptiion)

2023-07-28 10:54 UTC, shinonhorror commented on src/components/elements/header/header.tsx
> +const Header: React.FC = () => {
Данный элемент по архитектуре - это организм

2023-07-28 10:54 UTC, shinonhorror commented on src/components/elements/header/header.tsx
> +    <WarapHeader>
Синтаксическая ошибка, WrapHeader

2023-07-28 10:54 UTC, shinonhorror commented on src/components/elements/header/header.tsx
> +      </User>
Это все таки хэдер или футер?

2023-07-28 10:54 UTC, shinonhorror commented on src/components/elements/header/header.tsx
> +        <p className="small">© Parkonaft 2023</p>
Это касается также дальнейшей декомпозиции (т.е. можно определить новый атом для ссылок, например и тд)

2023-07-28 11:34 UTC, mrHoft commented on src/components/elements/header/header.tsx
> +`
Рано пока выносить: там есть временные элементы.

2023-07-28 11:37 UTC, mrHoft commented on src/components/elements/header/header.tsx
> +        <p className="small">© Parkonaft 2023</p>
Не понятно что именно ты комментируешь.
Если <p> то такой тег уже есть, создавать из него новый элемент смысла нет.
Если про класс с модификатором размера шрифта то на то он и класс.
Вообще смысл комментария не понятен.

2023-07-28 11:38 UTC, mrHoft commented on src/components/elements/header/header.tsx
> +const Header: React.FC = () => {
Это header. При чём тут организм?

2023-07-28 11:40 UTC, shinonhorror commented on src/components/elements/header/header.tsx
> +const Header: React.FC = () => {
мы используем атомарную архитектуру, в ее контексе header - это организм (папка organisms ), т.к. он состоит из других более маленьких компонентов.

2023-07-28 11:43 UTC, mrHoft commented
Если нет критических замечаний то не выдвигайте требования к исправлению,- достаточно комментария.

2023-07-29 10:44 UTC, alheym commented on src/components/elements/header/header.tsx
> +const Header: React.FC = () => {
> Это header. При чём тут организм?

мы утвердили методологию архитектуры, с которой согласились все
либо аргументируй, почему нам необходимо дополнительное деление на папки, с указанием этого в readme, либо придерживайся установленного формата

2023-07-29 10:48 UTC, alheym commented on src/components/elements/header/header.tsx
> +`
если есть временные элементы, то с какой целью ты их добавляешь?
для чего создавать дополнительную работу, а потом дополнительной задачей убирать этот мусор? 

кажется, ты сам просил разделять логику
соответственно, у тебя должен быть в папке header.component, header.styles, header.stories и так же index.ts для того, чтобы мы могли удобно работать с импортами, и не выносить каждый импорт на отдельную строку

если у тебя есть вопросы по архитектуре, ты всегда можешь их задать, тут все готовы помогать друг другу)

2023-07-29 10:52 UTC, alheym commented on src/components/elements/header/header.tsx
> +        <p className="small">© Parkonaft 2023</p>
мы используем styled components, что освобождает нас от всякого использования классов, а в том числе отдельных тегов, об этих преимуществах можно почитать в документации)

компонент для этого уже создан, а значит нужно использовать его, в этом и смысл декомпозиции и единоразового написания стилей для элементов

2023-07-29 10:54 UTC, alheym commented on src/components/elements/header/header.tsx
> +      </User>
для ссылок есть отличный компонент Link из react-router-dom, раз уж ты решил добавить эти элементы, то имеет смысл обернуть в полноценный компоненты

2023-07-29 11:09 UTC, alheym requested changes

2023-07-29 11:09 UTC, alheym commented on src/components/elements/header/header.tsx
> +  width: 100vw;
на странице появился горизонтальный скролл, почему?

2023-07-29 11:09 UTC, alheym commented on src/components/elements/header/header.tsx
> +  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 64 64' font-size='56' font-family='Arial' font-weight='400' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='64' height='64' rx='10'
почему не положить картинку в папку и импортировать в файл стилей?
когда поменяется лого, просто поменяем изображение в папке на актуальное

2023-07-29 11:09 UTC, alheym commented on src/components/elements/header/header.tsx
> +      <div>
что за div?
почему не завернуть в компонент и не переиспользовать в футере?

2023-07-29 12:56 UTC, merged