Ф-2 Подключить апи карт
car-parking-tracking/Parking.client pull request #9
Opened 2023-07-27 07:26 UTC by Tatty13

1. Task: Подключить апи карт
2. Screenshot: 
![Снимок экрана 2023-07-27 101849](https://github.com/car-parking-tracking/Parking.client/assets/91495653/538392af-9977-4ccb-a2d7-f70d87e338e0)

3. Was done:
  - [x] Подключено апи с помощью пакета @pbe/react-yandex-maps
  - [ ] Установлен пакет dotenv для хранения ключа (по документации настроить не получилось, выбрасывает ошибки)

2023-07-27 07:42 UTC, alheym requested changes

2023-07-27 07:42 UTC, alheym commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// import 'dotenv/config'
если это не нужно, то лучше удалить

2023-07-27 07:42 UTC, alheym commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
тут тоже

2023-07-27 07:42 UTC, alheym commented on src/components/organisms/ya-map/ya-map.component.tsx
> +        <Map {...mapConfig}></Map>
можно сразу закрыть, если ничего не помещаем внутрь
<Map {...mapConfig}/>

2023-07-27 07:42 UTC, alheym commented on src/components/templates/main/main.component.tsx
> +import { YaMap } from '../../organisms/ya-map'
тут нужно добавить экспорт в index.ts в корне папки organisms и тогда можно будет оставить просто '../../organisms' в дальнейшем мы сможем просто импортировать несколько компонентов сразу из папки

2023-07-27 07:42 UTC, alheym commented on src/components/templates/main/main.component.tsx
> +import { YaMap } from '../../organisms/ya-map'
уже в текущем файле можем избавиться от нескольких импортов
 import { YaMap, Modal } from '../../organisms'

2023-07-27 07:45 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +        <Map {...mapConfig}></Map>
Потом будут помещаться метки

2023-07-27 07:45 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// import 'dotenv/config'
Переменные окружения без этого будем реализовывать?

2023-07-27 07:46 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
Это задел на переменные окружения. Точно нужно удалить?

2023-07-27 07:48 UTC, alheym commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// import 'dotenv/config'
> Переменные окружения без этого будем реализовывать?

тут тогда нужно пометить как TODO и описать что и для чего
в противном случае комментарий смысловой нагрузки не несет

2023-07-27 07:55 UTC, Tatty13 commented on src/components/templates/main/main.component.tsx
> +import { YaMap } from '../../organisms/ya-map'
✅

2023-07-27 07:59 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// import 'dotenv/config'
Поняла, сейчас добавлю TODO

2023-07-27 08:03 UTC, alheym commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
> Это задел на переменные окружения. Точно нужно удалить?

тоже нужно добавить комментарий описывающий для чего это
либо уже добавлять весь код в рамках выполнения задачи по настройке переменных окружения

тут нужно понимать, что если ты знаешь для чего эта строчка, то человек который придет после тебя этого не знает и в идеале нужно сделать так, чтобы он не тратил время на разбирательство в твоем коде
в комментариях нет ничего плохого, но необходимо фиксировать для чего они были сделаны, маркеры так же облегчают поиск по коду, и вбив в поиске условное TODO ты сразу увидишь задачи, которые могли быть не зафиксированы в беклоге и не потеряешь этот код
так же это дает возможность членам твоей команды обратить внимание на эти строчки, они сразу понимают, что это не остаточный код и не "мусор", а задел под функциональность.

2023-07-27 08:07 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
Поняла, спасибо!

2023-07-27 08:14 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// import 'dotenv/config'
Решила вообще убрать, оставить только саму переменную (закомментированную в todo).

2023-07-27 08:17 UTC, alheym approved these changes

2023-07-27 08:17 UTC, alheym approved these changes

2023-07-27 08:24 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// import 'dotenv/config'
✅

2023-07-27 08:24 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
✅

2023-07-27 08:25 UTC, Tatty13 commented on src/components/organisms/ya-map/ya-map.component.tsx
> +        <Map {...mapConfig}></Map>
✅ добавила комментарий

2023-07-27 09:25 UTC, mrHoft commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
Да. Давайте сопровождать закомментированные блоки комментарием, но и без фанатизма: не стоит реагировать на каждый закомментированный блок: если автор ещё планирует работать над модулем то ему это, вероятно, нужно.

Помню меня слегка раздаржало каждый раз делать пометку "do not delete!" когда месяц работал над кодом и многое в нём переделывал а коллеги то prettier-ом по нему пройдутся то посчитают нужным "почистить" модуль в котором ни строчки не понимали. *накатило* :)

2023-07-27 09:26 UTC, mrHoft commented on src/components/organisms/ya-map/ya-map.component.tsx
> +        <Map {...mapConfig}></Map>
Опять же без фанатизма в подобных вопросах. А то дойдём до комментирования каждого своего действия.

2023-07-27 09:38 UTC, alheym commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
> Да. Давайте сопровождать закомментированные блоки комментарием, но и без фанатизма: не стоит реагировать на каждый закомментированный блок: если автор ещё планирует работать над модулем то ему это, вероятно, нужно.
> 
> Помню меня слегка раздаржало каждый раз делать пометку "do not delete!" когда месяц работал над кодом и многое в нём переделывал а коллеги то prettier-ом по нему пройдутся то посчитают нужным "почистить" модуль в котором ни строчки не понимали. _накатило_ :)

Для незаконченной работы есть опция создать отдельную ветку. 
Код который идет в ПР считается функциональным. Здорово, что ты можешь развивать закомментированный код целый месяц, но если не хочешь, чтобы его изменяли или удаляли, то держи в отдельном пространстве, где можешь работать обособленно, а потом отдельным ПР выкладывать на ревью.
Я особо не вижу практического смысла в том, чтобы какой то закомментированный код висел у нас как в текущей версии разработки, так и тем более попал в мейн. Никто не должен сидеть и думать над тем, нужен ли кому-то сейчас этот закомментированный фрагмент, или нет, если в нем нет соответствующих заметок.

2023-07-27 09:45 UTC, mrHoft approved these changes
Отличная работа!

2023-07-27 09:45 UTC, mrHoft commented on package.json
>    }
Это devDependencies.
Наш проект не предполагает запуск не скомпилированного кода. Поэтому всё что используем это devDependencies. Потом делаем `yarn build` и деплоим папку dist.
Если будем паковать в докер и поднимать в нём свой сервер то в dependencies пойдёт только то что нужно серверу.

2023-07-27 11:13 UTC, shinonhorror approved these changes

2023-07-28 10:45 UTC, mrHoft commented on src/components/organisms/ya-map/ya-map.component.tsx
> +// const { YAMAP_API_KEY = '' } = process.env
Есть такая штука как versioning. В релиз идут модули, работа над которыми ещё ведётся. Сейчас я сотрудничаю с Bethesda Softworks и там подобный подход в порядке вещей.

2023-07-28 10:48 UTC, merged